version: '3.1'

services:
  web:
    image: docker-flask
    ports:
      - '5000:5000'
    # healthcheck:
    #   test: curl --fail -s http://localhost:5000/ || exit 1
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3